spring:
    application:
      name: spring-jdbc-app
server:
    port: 5000

logging:
  file:
    name: logs/spring-boot-jdb-capp.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"

datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: admin
    password: password
    h2:
      console:
        settings:
          web-allow-others: true
      enabled: true
      path: /h2-console

