
datasource:
  url: jdbc:h2:mem:test
  driver-class-name: org.h2.Driver
  username: admin
  password: password
  h2:
      console:
          settings:
              web-allow-others: true
          enabled: true
          path: /h2